//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMarketGamePriceUpload.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.100.100.58;Initial Catalog=WebRepository;User ID=peter.robinson;Pa" +
            "ssword=P@$$w0rd1;")]
        public string WebRepoSQLConnection {
            get {
                return ((string)(this["WebRepoSQLConnection"]));
            }
            set {
                this["WebRepoSQLConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.usp_GetStockMarketGamePrices")]
        public string QueryProcedure {
            get {
                return ((string)(this["QueryProcedure"]));
            }
            set {
                this["QueryProcedure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jseweb_stock_price")]
        public string ProdTableName {
            get {
                return ((string)(this["ProdTableName"]));
            }
            set {
                this["ProdTableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string FieldTerminator {
            get {
                return ((string)(this["FieldTerminator"]));
            }
            set {
                this["FieldTerminator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\r\\n")]
        public string LineTerminator {
            get {
                return ((string)(this["LineTerminator"]));
            }
            set {
                this["LineTerminator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Data\\Waiting\\StockPrices.csv")]
        public string FileName {
            get {
                return ((string)(this["FileName"]));
            }
            set {
                this["FileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NumberOfLinesToSkip {
            get {
                return ((int)(this["NumberOfLinesToSkip"]));
            }
            set {
                this["NumberOfLinesToSkip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=127.0.0.1;Uid=probinson;Database=jsewebsite;Port=3333;Pwd=neB8Um5Jeg6oW9uB" +
            ";")]
        public string JseWebsiteTesting {
            get {
                return ((string)(this["JseWebsiteTesting"]));
            }
            set {
                this["JseWebsiteTesting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=127.0.0.1;Uid=probinson;Database=jsewebsite;Port=3333;Pwd=neB8Um5Jeg6oW9uB" +
            ";")]
        public string JseWebsiteTraning {
            get {
                return ((string)(this["JseWebsiteTraning"]));
            }
            set {
                this["JseWebsiteTraning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jseweb_stock_price")]
        public string TestingTableName {
            get {
                return ((string)(this["TestingTableName"]));
            }
            set {
                this["TestingTableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jseweb_stock_price")]
        public string TrainingTableName {
            get {
                return ((string)(this["TrainingTableName"]));
            }
            set {
                this["TrainingTableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Production,Training,Testing")]
        public string Environments {
            get {
                return ((string)(this["Environments"]));
            }
            set {
                this["Environments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=127.0.0.1;Uid=probinson;Database=jsewebsite;Port=3333;Pwd=neB8Um5Jeg6oW9uB" +
            ";")]
        public string JseWebSiteProd {
            get {
                return ((string)(this["JseWebSiteProd"]));
            }
            set {
                this["JseWebSiteProd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Host=Jamstockex.com;UserName=probinson;Port=22;Password=;PrivateKeyfilePath=C:\\Ke" +
            "ys\\PrivateKey-JamstockexSite_OpenSSHFormat.ppk;LocalForwardedPort=3333;RemoteHos" +
            "t=192.168.170.251;RemotePort=3306;")]
        public string ProductionSSHParams {
            get {
                return ((string)(this["ProductionSSHParams"]));
            }
            set {
                this["ProductionSSHParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM jseweb_stock_price WHERE  TradeDate IN (@Date)")]
        public string DestinationLookupQuery {
            get {
                return ((string)(this["DestinationLookupQuery"]));
            }
            set {
                this["DestinationLookupQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Host=testing.Jamstockex.com;UserName=probinson;Port=22;Password=;PrivateKeyfilePa" +
            "th=C:\\Keys\\PrivateKey-JamstockexSite_OpenSSHFormat.ppk;LocalForwardedPort=3333;R" +
            "emoteHost=192.168.170.251;RemotePort=3306;")]
        public string TraningSSHParams {
            get {
                return ((string)(this["TraningSSHParams"]));
            }
            set {
                this["TraningSSHParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Host=testing.jamstockex.com;UserName=probinson;Port=22;Password=;PrivateKeyfilePa" +
            "th=C:\\Keys\\PrivateKey-JamstockexSite_OpenSSHFormat.ppk;LocalForwardedPort=3333;R" +
            "emoteHost=192.168.170.251;RemotePort=3306;")]
        public string TestingSSHParams {
            get {
                return ((string)(this["TestingSSHParams"]));
            }
            set {
                this["TestingSSHParams"] = value;
            }
        }
    }
}
